"use client";
import {useEffect,useState} from "react";
import {staffFetch} from "@/lib/staff-api";
type RequestItem={id:string;vehicle:string;seller:string;kind:string;status:string;name:string;email:string;phone:string;message:string;preferred_at:string|null;offer_amount:string|null;internal_note:string;created_at:string};
export default function Requests(){
  const [items,setItems]=useState<RequestItem[]>([]),[filter,setFilter]=useState(""),[notice,setNotice]=useState("");
  const load=()=>staffFetch(`/api/v1/staff/buyer-requests/?page_size=48${filter?`&status=${filter}`:""}`).then(x=>setItems(x.results)).catch(()=>setNotice("Sign in again or retry."));
  useEffect(()=>{void load()},[filter]);
  async function update(item:RequestItem){const status=window.prompt("New status: new, contacted, scheduled or closed",item.status);if(!status)return;const note=window.prompt("Private activity note (optional)","")||"";try{await staffFetch(`/api/v1/staff/buyer-requests/${item.id}/`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,activity_note:note})});setNotice("Request updated.");void load()}catch{setNotice("Update failed. Check your permission and status value.")}}
  return <main className="reviewPage"><div className="staffTop"><div><span className="eyebrow">Support</span><h1>Buyer requests</h1><p>Marketplace support owns these requests and coordinates with sellers.</p></div><a href="/staff">Back to overview</a></div><div className="toolbar"><label>Status<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All statuses</option><option value="new">New</option><option value="contacted">Contacted</option><option value="scheduled">Scheduled</option><option value="closed">Closed</option></select></label>{notice&&<span role="status">{notice}</span>}</div>{items.length?<table className="dataTable"><thead><tr><th>Buyer</th><th>Vehicle</th><th>Request</th><th>Status</th><th>Received</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><strong>{x.name}</strong><br/><a href={`mailto:${x.email}`}>{x.email}</a><br/>{x.phone}</td><td>{x.vehicle}<br/><small>{x.seller}</small></td><td>{x.kind}{x.offer_amount&&<><br/><strong>₦{Number(x.offer_amount).toLocaleString()}</strong></>}</td><td><span className="statusChip">{x.status}</span></td><td>{new Date(x.created_at).toLocaleString("en-NG")}</td><td><button onClick={()=>update(x)}>Update</button></td></tr>)}</tbody></table>:<div className="empty"><h2>No requests in this view</h2><p>New enquiries, viewings and offers will appear here.</p></div>}</main>
}
